services:
  web:
    build: .
    image: cosmis/vitalapp_web:latest
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - vitalapp_db:/data/db

volumes:
  vitalapp_db:
